import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ScrollArea } from "@/components/ui/scroll-area";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-svh">
        <ScrollArea className="max-w-prose m-auto p-3 flex-1 flex flex-col w-full">

          {children}
        </ScrollArea>
      </body>
    </html>
  );
}
