import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex h-svh">
        <div className="max-w-prose m-auto p-3 flex-1">
          {children}

        </div>
      </body>
    </html>
  );
}
